### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by stuta** [Planning-nl/vugel-example#1]
npm install

npm ERR! Error while executing:
npm ERR! /usr/local/bin/git ls-remote -h -t ssh://git@github.com/Planning-nl/vue-loader.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

**Comment by basvanmeurs** [comment]
[fix](https://github.com/Planning-nl/vugel-example/commit/b816afb0cd9a5d0e40e56278819f0342fd9ee6a6)
